### ISSUE TITLE
翻訳作業メモ

### ISSUE THREAD

**Issue by howking** [Polymer-Japan/lit-html-docs-jp#1]
## ビルド方法

12/8 Cloud Buildで自動デプロイに対応

### Requirements

- [Cloud SDK](https://cloud.google.com/sdk/)
- [Jekyll](https://jekyllrb-ja.github.io/)

### Setup

```sh
git clone https://github.com/Polymer-Japan/lit-html-docs-jp
cd lit-html-docs-jp
git checkout -b jp-transrate
```

### Install

```sh
npm install
npm gen-docs
cd docs
npm run build
npm run serve # or jekyll serve -w
# deploy
gcloud app deploy
```
- [x] 12/7 現在Polymer-jp.orgのGCPプロジェクトで稼動できないか @aggre さんに確認をしてもらっている

### cloud buildの設定メモ

1. cloudbuild.yamlをつくっておき、
2. Source RepositoryでGitHubとの連携を設定
3. Cloud BuildのAPIを有効化して、
4. [IAM](https://console.cloud.google.com/iam-admin/iam?hl=ja&project=polymer-japan)の数字@cloudbuild.gserviceaccount.comに対してApp Engineの権限割り当て
5. Cloud Buildで「トリガー」を作成

## ステータス
- [x] [slack](https://polymer-jp.slack.com/)に報告、相談
- [x] _guide/03-template-reference.md 未着手
- [ ] _guide/04-concepts.md 現状ばっくり

## 作業予定
- [ ] 週明け(-12/10)までに全般的にある程度読める状態にする

## TODO
- [ ] jp-transrate -> jp-translate...
- [ ] 用語の使い方や統一の相談
- [ ] LitElementやPWA Starter Kitまでできるかな?
- [ ] 本家との相談

**Comment by howking** [comment]
進行をまとめた :arrow_right:  [201812 Polymerプロジェクト関連翻訳](/Polymer-Japan/translation/wiki/201812-Polymer-Project-JP-translate)
